name: CI

on: 
  push:
  fork:

jobs:
  test_links_utils:
    name: Check links in ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: setup python
      id: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.16'

    - name: setup environment
      id: setup_env
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-xdist requests jupyter lxml numpy matplotlib scipy sympy

    - name: check links
      id: links
      run: python -m pytest -n auto ./tests/test_check_links_in_ipynb.py ./utils/tests/

  badges:
    name: Add Google Colab Badges
    needs: test_links_utils
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: setup environment
      id: setup
      run: python -m pip install bs4 jupyter lxml

    - name: Add/Update badges
      id: badges
      run: python ./utils/add_colab_main_buttons.py

    - name: Commit & push
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message : Add Github badges or remove ipynb `id`s

  test_ipynb:
    needs: badges
    name: test ipynb on Google Colab
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      id: setup_env
      run: python -m pip install -r ./requirements.txt

    - name: pytest
      id: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      # run: python -m pytest -n auto -k 'not (links or update_nmisp_py)' ./tests
      run: python -m pytest -k 'not (links or update_nmisp_py)' ./tests
